--------------------------------------------------------
-- Archivo creado  - martes-noviembre-01-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "CARLOS"."EMPLOYEES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"GENDER_ID" NUMBER, 
	"JOB_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"BIRTHDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CARLOS.EMPLOYEES
SET DEFINE OFF;
Insert into CARLOS.EMPLOYEES (ID,GENDER_ID,JOB_ID,NAME,LAST_NAME,BIRTHDATE) values (4,1,2,'Jose','Gonzalez',to_date('09/09/87','DD/MM/RR'));
Insert into CARLOS.EMPLOYEES (ID,GENDER_ID,JOB_ID,NAME,LAST_NAME,BIRTHDATE) values (1,1,3,'Jose','Martinez',to_date('20/05/90','DD/MM/RR'));
Insert into CARLOS.EMPLOYEES (ID,GENDER_ID,JOB_ID,NAME,LAST_NAME,BIRTHDATE) values (2,2,2,'Adriana','Perez',to_date('12/08/88','DD/MM/RR'));
Insert into CARLOS.EMPLOYEES (ID,GENDER_ID,JOB_ID,NAME,LAST_NAME,BIRTHDATE) values (3,1,1,'Luis','Cavazos',to_date('02/02/86','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARLOS"."EMPLOYEES_PK" ON "CARLOS"."EMPLOYEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "CARLOS"."EMPLOYEES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CARLOS"."EMPLOYEES" MODIFY ("GENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEES" MODIFY ("JOB_ID" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEES" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "CARLOS"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_FK_GENDER" FOREIGN KEY ("GENDER_ID")
	  REFERENCES "CARLOS"."GENDERS" ("ID") ENABLE;
  ALTER TABLE "CARLOS"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_FK_JOBS" FOREIGN KEY ("JOB_ID")
	  REFERENCES "CARLOS"."JOBS" ("ID") ENABLE;
