--------------------------------------------------------
-- Archivo creado  - martes-noviembre-01-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE_WORKED_HOURS
--------------------------------------------------------

  CREATE TABLE "CARLOS"."EMPLOYEE_WORKED_HOURS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMPLOYEE_ID" NUMBER, 
	"WORKED_HOURS" NUMBER, 
	"WORKED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CARLOS.EMPLOYEE_WORKED_HOURS
SET DEFINE OFF;
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (1,1,8,to_date('03/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (2,1,8,to_date('04/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (3,1,8,to_date('05/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (4,1,8,to_date('06/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (5,1,8,to_date('07/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (6,1,8,to_date('08/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (7,1,8,to_date('09/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (8,1,8,to_date('10/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (9,1,8,to_date('11/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (10,1,8,to_date('12/10/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (11,2,8,to_date('26/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (12,2,8,to_date('27/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (13,2,8,to_date('28/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (14,2,8,to_date('29/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (15,2,8,to_date('30/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (16,3,8,to_date('05/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (17,3,8,to_date('06/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (18,3,8,to_date('07/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (19,3,8,to_date('08/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (20,3,8,to_date('09/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (21,3,8,to_date('10/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (22,3,8,to_date('11/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (23,3,8,to_date('12/09/22','DD/MM/RR'));
Insert into CARLOS.EMPLOYEE_WORKED_HOURS (ID,EMPLOYEE_ID,WORKED_HOURS,WORKED_DATE) values (24,3,8,to_date('13/09/22','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index EMPLOYEE_WORKED_HOURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARLOS"."EMPLOYEE_WORKED_HOURS_PK" ON "CARLOS"."EMPLOYEE_WORKED_HOURS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_WORKED_HOURS
--------------------------------------------------------

  ALTER TABLE "CARLOS"."EMPLOYEE_WORKED_HOURS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEE_WORKED_HOURS" ADD CONSTRAINT "EMPLOYEE_WORKED_HOURS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CARLOS"."EMPLOYEE_WORKED_HOURS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEE_WORKED_HOURS" MODIFY ("WORKED_HOURS" NOT NULL ENABLE);
  ALTER TABLE "CARLOS"."EMPLOYEE_WORKED_HOURS" MODIFY ("WORKED_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEE_WORKED_HOURS
--------------------------------------------------------

  ALTER TABLE "CARLOS"."EMPLOYEE_WORKED_HOURS" ADD CONSTRAINT "EMPLOYEE_WORKED_HOURS_FK1" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "CARLOS"."EMPLOYEES" ("ID") ENABLE;
